// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: store.proto
#ifndef GRPC_store_2eproto__INCLUDED
#define GRPC_store_2eproto__INCLUDED

#include "store.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace store {

// The store service definition.
class Store GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Requests list of prices fro a product from store, for different vendors registered at the store
    virtual ::grpc::Status getProducts(::grpc::ClientContext* context, const ::store::ProductQuery& request, ::store::ProductReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::store::ProductReply>> AsyncgetProducts(::grpc::ClientContext* context, const ::store::ProductQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::store::ProductReply>>(AsyncgetProductsRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::store::ProductReply>* AsyncgetProductsRaw(::grpc::ClientContext* context, const ::store::ProductQuery& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status getProducts(::grpc::ClientContext* context, const ::store::ProductQuery& request, ::store::ProductReply* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::store::ProductReply>> AsyncgetProducts(::grpc::ClientContext* context, const ::store::ProductQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::store::ProductReply>>(AsyncgetProductsRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::store::ProductReply>* AsyncgetProductsRaw(::grpc::ClientContext* context, const ::store::ProductQuery& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_getProducts_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Requests list of prices fro a product from store, for different vendors registered at the store
    virtual ::grpc::Status getProducts(::grpc::ServerContext* context, const ::store::ProductQuery* request, ::store::ProductReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_getProducts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_getProducts() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_getProducts() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getProducts(::grpc::ServerContext* context, const ::store::ProductQuery* request, ::store::ProductReply* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetProducts(::grpc::ServerContext* context, ::store::ProductQuery* request, ::grpc::ServerAsyncResponseWriter< ::store::ProductReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_getProducts<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_getProducts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_getProducts() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_getProducts() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getProducts(::grpc::ServerContext* context, const ::store::ProductQuery* request, ::store::ProductReply* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace store


#endif  // GRPC_store_2eproto__INCLUDED
